# author:Levi
# 搭配convert js to sgmodule.py使用。可将qx的js/conf/snippet文件转换为sgmodule文件。使用方法见博客。

name: convert js to sgmodule

on:
  push:
    paths:
      - 'scripts/**' # Trigger on changes in scripts folder
  pull_request:
    paths:
      - 'Surge/**' # Trigger on changes in surge folder
  workflow_dispatch:

jobs:
  generate_sgmodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run script
        run: python .github/scripts/convert_js_to_sgmodule.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sgmodule-artifacts
          path: ${{ github.workspace }}/Surge




      # 在添加更改前打印出所有未跟踪的文件，确认生成的 sgmodule 文件是否出现
      - name: List all untracked files
        run: |
          echo "List of all untracked files:"
          git status --porcelain

      # 添加所有变更到暂存区
      - name: Add all changes
        run: |
          git add -A

      # 提交变更，如果有的话
      - name: Commit and push changes
        run: |
          if [ -n "$(git diff --staged --name-only)" ]; then
              echo "There are changes to commit."
              git config user.name "${{ github.actor }}"
              git config user.email "${{ github.actor }}@users.noreply.github.com"
              git commit -m "自动提交: 已转换为sgmodule文件"
              git push origin HEAD:main
          else
              echo "No changes to commit.没有变动，跳过提交和推送步骤。"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




      - name: Trigger next workflow convert_js_to_plugin
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: convert_js_to_plugin.yml
          token: ${{ secrets.GITHUB_TOKEN }}    
