# author:Levi
# 搭配convert js to sgmodule.py使用。可将qx的js/conf/snippet文件转换为sgmodule文件。使用方法见博客。

name: convert js to sgmodule

on:
  push:
    paths:
      - 'scripts/**' # Trigger on changes in scripts folder
  pull_request:
    paths:
      - 'Surge/**' # Trigger on changes in surge folder
  workflow_dispatch:

jobs:
  generate_sgmodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run script
        run: python .github/scripts/convert_js_to_sgmodule.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sgmodule-artifacts
          path: ${{ github.workspace }}/Surge

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: sgmodule-artifacts
          path: Surge


      - name: Add and commit changes
        run: |
          cd Surge
          git add -A
          git diff --staged --name-only
          if [ -n "$(git diff --staged --name-only)" ]; then
              echo "存在变动，进行提交。"
              git config user.name "${{ github.actor }}"
              git config user.email "${{ github.actor }}@users.noreply.github.com"
              git commit -m "自动生成并添加 sgmodule 文件"
              git push --force
          else
              echo "没有新的变动，不进行提交。"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Trigger next workflow convert_js_to_plugin
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: convert_js_to_plugin.yml
          token: ${{ secrets.GITHUB_TOKEN }}    
